staging:
  type: deploy
  environment:
    name: dev-staging
  only:
    - deploy
  tags:
    - dev
    - rails
  script:
    - cd /home/michaelchan/PolyFYPman/
    - git pull
    - bundle install
    - yarn install
    - rails db:migrate
    - rails assets:precompile
    - /usr/bin/service apache2 reload
