staging:
  type: deploy
  environment:
    name: dev-staging
  only:
    - deploy
  tags:
    - dev
    - rails
  script:
    - cd /home/michaelchan/PolyFYPman/
    - git pull
    - bundle install
    - yarn install
    - rails db:migrate:reset
    - rails assets:precompile
    - sudo service apache2 reload
    - sudo pkill -f "rake jobs:work"
    - curl https://langcapadmin.edc.polyu.edu.hk -k
